name: Labeler

on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Add "invite me to the organization" label
        if: github.ref == 'refs/heads/main'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: invite me to the organization
